### ISSUE TITLE
UTF-8 characters in the file are not returned correctly.

### ISSUE THREAD

**Issue by lruzicka** [sciurius/perl-File-LoadLines#4]
I have got a text file with lines using utf-8, see attachments. 
When I try to read it using the following code:

~~~
use File::LoadLines;

my $options = {"encoding" => "utf-8"};
my @lines = loadlines("test.txt", $options);

foreach (@lines) {
    print("$_\n");
}

print("Sádlo, práce, řeřicha, řízek, čížek");
~~~

Instead of getting the words spellt out correctly, I am getting wrong characters instead.

Reproducible: Always

Steps to Reproduce:
1. Try to read a file with non-ascii characters (utf-8)
2. Print it out -> you will get warnings and possibly mismatches.

Actual Results:  
See attachments.

Expected Results:  
Works without issues.

When you take a look at the attachment that shows the `cat test.txt` operation, you will see that the national characters are correctly shown and that the system is capable of showing them.

Compare it with the output of the above mentioned perl script. You can see that some of the characters are replaced with the stylized question mark character, while others are printed with a warning saying "Wide character in print."

What is interesting, when the warning is shown, the characters are printed out correctly. Also, printing just a plain string that uses these characters is flawless, therefore I assume that the problem is not within Perl itself.

![cat_test_file](https://github.com/sciurius/perl-File-LoadLines/assets/24384878/04c63886-948d-472c-87fa-4fffe5102df3)

![loadlines](https://github.com/sciurius/perl-File-LoadLines/assets/24384878/f4b4027d-3558-413f-bc74-96600898be46)

[loadlines.tar.gz](https://github.com/sciurius/perl-File-LoadLines/files/13487523/loadlines.tar.gz)

**Comment by sciurius** [comment]
Thanks for the report. 
`loadlines` reads the file, decodes the data, and returns the content in the array `@lines`. The array contains data in Perl internal encoding.
When printing the lines to STDOUT you need to encode them from Perl internal encoding to e.g. UTF-8.
````
binmode STDOUT => 'utf8';
foreach (@lines) {
    print("$_\n");
}
````
Now the data from the file comes out as you expect.

The last line of the program is misleading. You may think these are UTF-8 characters but they are not. For this you need to add the `use utf8` pragma. 

For your convenience I have attached a corrected program.
[loadlines-fixed.tar.gz](https://github.com/sciurius/perl-File-LoadLines/files/13488206/loadlines-fixed.tar.gz)
